In [71]:
import pandas as pd
import ptable as pt
import numpy as np

In [ ]:
df = pd.read_csv('path/to/your/X_train.csv')

In [ ]:
df = df.iloc[:, :-12]
df

In [104]:
import pandas as pd
import ptable as pt
import numpy as np

name_ids = {}
name_ele = {}
for i in pd.read_csv('./all_component.csv').values:
    try:
        name_ids[i[1]] = int(i[0])
        name_ele[i[0]] = i[1]
    except:
        name_ids[i[1]] = None
        name_ele[i[0]] = None

def formula_to_idx(list1):
    return [name_ids[i] for i in list1]

def idx_to_formula(list2):
    return [name_ele[j] for j in [str(i) for i in list2]]

In [105]:
## Read dataframe
my_df = df
# print(my_df.columns)
#Identify keys (columns) common to both the DataFrame and the dictionary
common_columns = set(my_df.columns[:-1]).intersection(name_ids.keys())

# Create a new dictionary for renaming columns using the common keys
column_rename_dict = {old_col: name_ids[old_col] for old_col in common_columns}

# Rename columns based on the new dictionary
my_df.rename(columns=column_rename_dict, inplace=True)
print(my_df.columns)
X_comp = my_df.values[:,:-1]

glass_id = [int(i) for i in (my_df.columns.to_list()[:-1])]

comp_x_desc, eles, count = pt.get_descriptor(idx_to_formula(glass_id))
n_x_desc = np.dot(X_comp,comp_x_desc.values)
n_x_desc = pd.DataFrame(n_x_desc,columns = comp_x_desc.columns)
n_x_desc[['O_per', 'NF_per', 'NM_per',]] /= n_x_desc[['O_per', 'NF_per', 'NM_per',]].values.sum(axis=1).reshape(-1,1)

X_descr = n_x_desc
pd.concat([X_descr, my_df.iloc[:,-1]], axis=1).to_csv('descriptor.csv', index=False)

Index([       1,        2,        8,        3,        5,       75,        7,
              9,        4,       32,      436,       81,       71,       37,
             92,       24,       35,       38,       51,       55,       72,
             23,       39,       77,       79,        6,       58,       66,
            121,       59,      507,       82,      135,      134,      517,
            509,       91,       80,      111,       76,      123,       22,
            132,       34,     1001,       42,       57,       60,     1000,
             36,      122,     1002,       33, 'others'],
      dtype='object')

In [106]:
pd.read_csv('descriptor.csv')

,O_per,NF_per,NM_per,valency_NF,valency_NM,automic_mass,automic_vol,A_number,automic_radius,vdwall_radius,covalent_radius,element_dipole_polarizability,others
0,0.609913,0.261546,0.128541,303.923329,50.290865,6467.175823,2574.135538,3153.651220,645.349253,576.168187,286.962684,10778.796839,0.0
1,0.620603,0.275342,0.104055,324.636238,39.372142,6924.329402,2539.043898,3361.007917,640.580867,577.635997,282.191674,9782.279834,0.0
2,0.604377,0.273450,0.122172,323.059845,45.288333,6604.198935,2523.507004,3213.877903,638.158038,575.474416,283.198892,10431.874984,0.0
3,0.619563,0.287351,0.093086,340.420000,36.380000,6541.201776,2602.370207,3225.140000,651.771400,588.184300,288.011100,9732.250000,0.0
4,0.682890,0.213178,0.103932,221.199896,47.324662,6432.247092,2423.861369,3173.852364,571.901667,501.744786,255.989219,8551.578567,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,0.607871,0.244406,0.147723,279.521217,56.497294,6255.325773,2497.868188,3060.020852,620.186986,551.894312,279.023234,10875.862961,0.0
103,0.593255,0.210972,0.195773,239.113395,80.559052,6505.357121,2453.594040,3226.036357,564.728493,516.637668,275.295819,14916.570013,0.0
104,0.617513,0.287388,0.095099,339.614866,36.750077,6431.140974,2572.020281,3174.015679,644.709894,582.317590,285.091311,9637.108881,0.0
105,0.612135,0.297689,0.090176,362.680653,31.738332,6872.752782,2634.426361,3347.353522,672.821223,611.911133,295.509451,10075.376768,0.0
106,0.638237,0.177808,0.183955,197.881917,67.372042,6811.560954,2604.930135,3297.652278,613.361696,538.578072,283.372624,12901.071966,0.0

In [52]:
data = pd.read_csv("descriptor.csv")

In [53]:
data

,O_per,NF_per,NM_per,valency_NF,valency_NM,automic_mass,automic_vol,A_number,automic_radius,vdwall_radius,covalent_radius,element_dipole_polarizability,others
0,0.685236,0.211163,0.103601,216.613613,47.672504,6438.844555,2414.976549,3175.511007,568.718023,498.318225,254.259220,8426.395071,0.00
1,0.603664,0.298321,0.098015,353.800000,38.000000,6282.364155,2506.336161,3101.800000,631.259000,572.999000,278.912000,9476.820000,0.00
2,0.617599,0.250081,0.132320,289.180000,46.640000,6287.318462,2552.947154,3082.560000,627.537300,559.548600,282.565700,11422.600250,1.29
3,0.600054,0.268403,0.131543,317.750292,46.946553,6765.313200,2626.046680,3265.348425,658.278360,591.052874,293.885691,11987.770432,0.00
4,0.604377,0.273450,0.122172,323.059845,45.288333,6604.198935,2523.507004,3213.877903,638.158038,575.474416,283.198892,10431.874984,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,0.617599,0.250081,0.132320,289.180000,46.640000,6287.318462,2552.947154,3082.560000,627.537300,559.548600,282.565700,11422.600250,1.29
103,0.593255,0.210972,0.195773,239.113395,80.559052,6505.357121,2453.594040,3226.036357,564.728493,516.637668,275.295819,14916.570013,0.00
104,0.617513,0.287388,0.095099,339.614866,36.750077,6431.140974,2572.020281,3174.015679,644.709894,582.317590,285.091311,9637.108881,0.00
105,0.616891,0.287026,0.096083,342.600000,37.200000,6328.052894,2565.356662,3131.600000,645.452000,583.406000,285.136000,9568.140000,0.00
106,0.614702,0.257948,0.127350,299.540000,49.000000,6910.962648,2619.484939,3360.110000,647.057300,582.434700,290.371000,11337.439500,0.00